UNKNOWN_TOPIC = "desconocida"

TOPIC_CATALOG = {
    "astronomia_universo": "Astronomía, universo, Big Bang, galaxias, estrellas, planetas, cosmología, espacio, sistema solar.",
    "ciencia_general": "Ciencia general, investigación, método científico, experimentos, teorías, hipótesis, laboratorio.",
    "fisica": "Física, energía, fuerza, movimiento, gravedad, relatividad, mecánica cuántica, ondas, electricidad.",
    "quimica": "Química, átomos, moléculas, reacciones químicas, enlaces, ácidos, bases, pH, redox, química orgánica.",
    "biologia": "Biología, seres vivos, células, ADN, genética, evolución, ecosistemas, organismos, bioética, clonación.",
    "medicina_salud": "Medicina, salud, pacientes, enfermedades, diagnóstico, tratamiento, hospitales, médicos, clínica.",
    "psicologia": "Psicología, mente, conducta, emociones, ansiedad, depresión, terapia, personalidad, salud mental.",
    "educacion": "Educación, alumnos, profesores, cursos, asignaturas, aprendizaje, evaluación, universidad, docencia.",
    "matematicas": "Matemáticas, álgebra, cálculo, geometría, estadística, probabilidad, ecuaciones, funciones.",
    "tecnologia": "Tecnología, software, hardware, sistemas digitales, dispositivos, plataformas, innovación.",
    "programacion": "Programación, código, Python, Java, JavaScript, API, backend, frontend, frameworks, errores.",
    "inteligencia_artificial": "IA, machine learning, deep learning, LLM, RAG, embeddings, modelos generativos, agentes.",
    "ciberseguridad": "Ciberseguridad, malware, phishing, vulnerabilidades, cifrado, ataques, firewall, privacidad.",
    "redes_sistemas": "Redes, sistemas, IP, DNS, servidores, routers, Linux, protocolos, infraestructura, DevOps.",
    "legal": "Derecho, leyes, contratos, cláusulas, normativa, obligaciones, demandas, sentencias, aspectos jurídicos.",
    "finanzas": "Finanzas, inversión, ingresos, gastos, presupuesto, rentabilidad, bancos, capital, deuda.",
    "contabilidad": "Contabilidad, cuentas, debe, haber, activo, pasivo, patrimonio, IVA, balances, asientos contables.",
    "economia": "Economía, mercado, oferta, demanda, inflación, PIB, recesión, crecimiento, política fiscal.",
    "rrhh": "Recursos humanos, empleados, nóminas, contratación, entrevistas, salarios, desempeño, vacaciones.",
    "marketing": "Marketing, publicidad, campañas, marca, SEO, redes sociales, audiencia, conversión, clientes.",
    "ventas": "Ventas, clientes, leads, CRM, pipeline, negociación, propuestas, ofertas, facturación.",
    "empresa_negocio": "Empresa, negocio, estrategia, gestión, operaciones, KPIs, liderazgo, organización, emprendimiento.",
    "proyectos": "Gestión de proyectos, tareas, hitos, cronogramas, Scrum, Kanban, entregables, riesgos.",
    "logistica": "Logística, almacenes, inventario, stock, distribución, transporte, pedidos, cadena de suministro.",
    "industria_ingenieria": "Ingeniería, industria, producción, fabricación, mantenimiento, máquinas, procesos, automatización.",
    "arquitectura_construccion": "Arquitectura, construcción, obras, edificios, planos, estructuras, viviendas, licencias.",
    "energia_medioambiente": "Energía, medioambiente, sostenibilidad, renovables, cambio climático, emisiones, contaminación.",
    "agricultura": "Agricultura, cultivos, cosechas, ganadería, riego, suelo, fertilizantes, granjas.",
    "alimentacion_nutricion": "Alimentación, nutrición, dieta, alimentos, proteínas, vitaminas, calorías, recetas.",
    "historia": "Historia, guerras, revoluciones, imperios, civilizaciones, siglos, colonización, edad media.",
    "filosofia": "Filosofía, ética, moral, conocimiento, existencia, razón, metafísica, pensamiento.",
    "literatura": "Literatura, novelas, poesía, cuentos, autores, personajes, narradores, obras literarias.",
    "arte_cultura": "Arte, cultura, pintura, escultura, museos, artistas, patrimonio, exposiciones.",
    "musica": "Música, canciones, álbumes, ritmo, melodía, instrumentos, conciertos, compositores.",
    "cine_medios": "Cine, películas, series, guion, directores, actores, televisión, medios audiovisuales.",
    "deporte": "Deporte, fútbol, baloncesto, tenis, entrenamiento, partidos, equipos, competición.",
    "turismo_viajes": "Turismo, viajes, hoteles, destinos, vuelos, reservas, itinerarios, vacaciones.",
    "geografia": "Geografía, países, continentes, ríos, montañas, mapas, clima, población, territorios.",
    "politica": "Política, gobiernos, partidos, elecciones, parlamento, democracia, ministros, leyes.",
    "administracion_publica": "Administración pública, trámites, ayuntamientos, expedientes, subvenciones, funcionarios.",
    "seguros": "Seguros, pólizas, primas, siniestros, coberturas, aseguradoras, indemnizaciones.",
    "inmobiliario": "Inmobiliario, viviendas, alquiler, compraventa, hipotecas, propiedades, inmuebles.",
    "transporte": "Transporte, trenes, aviones, barcos, autobuses, rutas, pasajeros, mercancías.",
    "automocion": "Automoción, coches, vehículos, motores, combustible, baterías, talleres, reparación.",
    "telecomunicaciones": "Telecomunicaciones, fibra, móvil, 5G, internet, antenas, operadores, redes móviles.",
    "videojuegos": "Videojuegos, consolas, gameplay, jugadores, niveles, personajes, PlayStation, Xbox.",
    "moda": "Moda, ropa, calzado, marcas, tendencias, diseño textil, colecciones, estilo.",
    "religion": "Religión, fe, iglesias, Dios, Biblia, islam, cristianismo, budismo, creencias.",
    "seguridad_laboral": "Seguridad laboral, prevención de riesgos, accidentes laborales, EPIs, salud laboral."
}

ALLOWED_TOPICS = list(TOPIC_CATALOG.keys()) + [UNKNOWN_TOPIC]